version: '3.8'

services:
  backend:
    build:
      context: ./todo_backend
    container_name: backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./todo_frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
