name: Deploy to Testing

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Docker Image
        run: |
          docker build -t todo-backend ./todo_backend
          docker tag todo-backend:latest 373516853296.dkr.ecr.eu-north-1.amazonaws.com/todo-backend:latest

      - name: Build Frontend Docker Image
        run: |
          docker build -t todo-frontend ./todo_frontend
          docker tag todo-frontend:latest 373516853296.dkr.ecr.eu-north-1.amazonaws.com/todo-frontend:latest

      - name: Push Backend Docker Image
        run: |
          docker push 373516853296.dkr.ecr.eu-north-1.amazonaws.com/todo-backend:latest

      - name: Push Frontend Docker Image
        run: |
          docker push 373516853296.dkr.ecr.eu-north-1.amazonaws.com/todo-frontend:latest

      - name: Deploy Application on Testing EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TESTING_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/mern-todo-app-team

            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 373516853296.dkr.ecr.eu-north-1.amazonaws.com

            docker-compose pull

            docker-compose down

            docker-compose up -d
